### PR TITLE
Method to check if Google Play is supported at runtime

### PR DESCRIPTION
**Pull request by JamesMcMahon**
See https://github.com/playgameservices/play-games-plugin-for-unity/issues/1346

Just wanted to get the ball rolling on this feature. I have no idea how to implement this on iOS and the code for Android is written by @alamboley.

### CODE REVIEW

**Comment by alamboley** [comment]
Nice 👍, I think it isn't requested for iOS since the whole framework is embedded in the app, right?

**Comment by JamesMcMahon** [comment]
Yeah that would make sense. It may be as simple as just returning true on iOS.

So my TODO comments may be inaccurate. I can make a few changes to this as needed.

**Comment by JamesMcMahon** [comment]
@claywilkinson We had some back on forth in https://github.com/playgameservices/play-games-plugin-for-unity/issues/1346 but I'd like to move future discussion into this PR. Just to make it easier to follow in the future.

What do I need to change in order to move forward with getting this merged in?

**Comment by claywilkinson** [comment]
The code is OK - but I think the method should either be integrated into NativeClient so it similar in structure to all the other methods, or moved to a utility class.

**Comment by JamesMcMahon** [comment]
My  concern with putting it in the NativeClient is that in my case, I don't actually access the client directly. Here is an example of my auth code:

```cs
if (!Social.localUser.authenticated)
{
#if UNITY_ANDROID
    // Check if supported because some devices will not have it installed
    if (GooglePlayGamesSupported)
    {        
        GooglePlayGames.PlayGamesPlatform.Activate();
        GooglePlayGames.PlayGamesPlatform.Instance.Authenticate(PostAuthenticate, silent);
    }
#else
    Social.localUser.Authenticate(PostAuthenticate);
#endif
}
```

In this case the `GooglePlayGamesSupport` property is a custom version of the code in this PR.
Note I never access native client directly.

So a Utility method may make the most sense. Do you have a specific Utility class that I should add the method to or should I create new Utility class? If the latter what would you prefer in terms of location and naming?

**Comment by claywilkinson** [comment]
I think a new class in Assets/GooglePlayGames/OurUtils might be the easiest.  I'll leave the naming to you - maybe something like PlayServiceUtils?

**Comment by JamesMcMahon** [comment]
Excuse the slow turn around on this. I have been swamped lately. I am hoping to make the suggested edits soon.

**Comment by JamesMcMahon** [comment]
@claywilkinson Ok changes made, let me know how it looks.

**Comment by LoungeKatt** [comment]
Is it entirely necessary to check if the Google Play Games app is installed? It seems like an "expensive" check and it would appear Google deprecated their own services verification with the new design.

**Comment by JamesMcMahon** [comment]
Yeah I think it's helpful. I am personally using it my game to ensure different behavior if Google Play isn't installed.

**Comment by JamesMcMahon** [comment]
@claywilkinson Any further changes that you would recommend?

**Comment by claywilkinson** [comment]
Thanks!

**Pull request merged**
