### PR TITLE
Brute force.ish way to get LoadScore() func. to work

### PR DESCRIPTION
**Pull request by Tedwikman**

### CODE REVIEW

**Comment by Tedwikman** [comment]
For the @googlebot 
I've signed it!

**Comment by claywilkinson** [comment]
Hi @Tedwikman  - Thanks for the pull request!  I have a couple high level comments that I hope you can address and then we can merge it in!
First - it looks like your merging of the latest code into your branch did not work correctly.  Some of your changes are reversions of other pull requests.  Can you review the diffs and make sure the changes you are making are actually needed to make LoadScore() work, and revert the changes that are not needed.

Second, we are using native libraries to access the game services API now and not GMSCore directly via JNI.  This is done to keep the iOS and Android functionality the same with the minimal amount of maintenance.   Can you map the calls you are making to Java to the ones in the NativeClients?  I believe all the APIs should be exposed at a low level.

Let me know if you have questions, or need help pointing out specific issues in the code.

**Comment by Tedwikman** [comment]
Hi @claywilkinson 
Now I have updated the branch to include the changes which was in the main branch but got removed with my merge. 

I have also removed the majority of methods I used to call Android methods to make the overall code cleaner. 

I have however not the knowledge to switch the calls into native calls, so I have wrapped the android calls in directives. Hopefully this is good enough for a first iteration.

**Comment by Tedwikman** [comment]
@claywilkinson Now I have moved the GetStatus to PlayGamesHelperObject.
I don't have any ability to test on iOS so hopefully someone else could help out with that part.

**Comment by fixed** [comment]
Is this going anywhere? I would love to have this functionality

**Comment by Tedwikman** [comment]
Hey hey, I am currently slammed with work at my company, but I will hopefully have some time in a week or two. In the meantime feel free to try out the current iteration. Ive made a unitypackage which you can download from the repo and unpack.

**Comment by fixed** [comment]
Hey Ted, thanks for the update!
I will try the latest commit this week, then.

**Comment by claywilkinson** [comment]
This has been integrated in the 0.9.25 version of the plugin.

**Pull request closed without merging**
