### PR TITLE
Automagically add .framework and .bundle files / folders xCode

### PR DESCRIPTION
**Pull request by LeshM**

### CODE REVIEW

**Comment by claywilkinson** [comment]
Thanks @LeshM I think this is headed in the right direction, but I don't think we want to require Python to do an iOS build.  Is there a way you can do the same thing with just using C#?

**Comment by LeshM** [comment]
This should only run on a mac or on Unity Cloud Build, which has python by default.
I believe it can be rewritten to run without python, but as we currently have no available resources we can't do that right now :/

**Comment by claywilkinson** [comment]
Thanks for the quick response @LeshM  -  Let me mark this as an enhancement for the time being.

**Comment by TimBayer** [comment]
This would be a great enhancement, but I agree, you should not count on this running on just a mac or Unity Cloud.  We use Jenkins on Windows to build our xcode/android projects, then another Jenkins node on a mac to do the actual xcode build.  

I'm working on a way using Unity's Xcode api to pull in the framework/bundles in a postprocess script.  The actual framworks reside in the Unity project in a a neighbor directory to Assets.  I think I'm getting close but am running into the issues I posted in #450 .  I'll post back if I get this working.

**Comment by claywilkinson** [comment]
@TimBayer  and @LeshM  - I am seeing a lot of people using CocoaPods - https://cocoapods.org/.
It uses Ruby (which is standard on the Mac).  I could do a PR if you think it would be helpful.

I am thinking it would run the pod  update step at the end of the Unity build.  The only tradeoff I can see is that you need to close Xcode and open the xcworkspace vs. the xcproject file.

Thoughts?

**Comment by claywilkinson** [comment]
Closing this PR - cocoapods is added to the plugin processing, so if it is installed, it will create a project workspace to build the app with the correct dependencies.

**Pull request closed without merging**
