### PR TITLE
Added OnConnectionFailedListener to TokenFragment class. #1836

### PR DESCRIPTION
**Pull request by muscly**
A fix for #1836 

In 0.9.39a, you changed the calling order of TokenClient.FetchTokens() and InitializeGameServices() in NativeClient.cs.
But TokenFragment (in TokenFragment.java)  has no connection failure listener. So, if a connection failure occurs TokenClient.FetchTokens() never calls the callback. Furthermore, the "Install Google Play Games" dialog is not displayed.

I added a connection failure listener to TokenFragment. And I used the Google SignIn Intent to display the "Install Google Play Games" dialog. I wanted to call ConnectionResult.startResolutionForResult() but I couldn't do it with a Fragment. I'd like to hear your feedback about this.

### CODE REVIEW

**Comment by y3102sof** [comment]
This problem still occur in 0.9.40. It's not applied yet?

**Comment by Temka193** [comment]
Please apply this request!

**Comment by claywilkinson** [comment]
Thanks @muscly  - can you remove unity packages (the binary files) from the pull request?  I'll merge and rebuild in the next couple of days.

**Comment by muscly** [comment]
I removed the unity packages. But it seems like that someone has already applied the patch.

**Pull request closed without merging**
