### PR TITLE
Some methods implemented: CurrentScoreValueByRanking.

### PR DESCRIPTION
**Pull request by natamelo**

### CODE REVIEW

**Comment by natamelo** [comment]
I've signed it!

**Comment by claywilkinson** [comment]
@natamelo - Was the  CLA signed as a company?  When I check for your username, I don't see it.

**Comment by natamelo** [comment]
I did with my username.

**Comment by natamelo** [comment]
Ok. I am sorry. I will do as soon as.

**Comment by Houssamix** [comment]
I signed it! 

Thanks, your CLA has been submitted.

**Comment by claywilkinson** [comment]
These changes have been integrated by another commit, so I am closing this one.  Thanks for the pull request, it really helped keeping things moving.

**Pull request closed without merging**
